# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1STuDN1hSkXDWt16BEYJBKrCOxk4hLvzF
"""

contacts={
    "names" : {"name 1" : "Ahmed " , "name 2" : "Mohamed" },
    "Numbers" : {"num1" : "0100765345" , "num2" : "0118373637"}
    }

contacts["names"] . update({"name 3" : "Ali" , "name 4" : "Marwa" , "name 5" : "Noor"})
contacts["Numbers"]. update({"num3": "0120988838" , "num4" : "01073637383" , "num5" : "0127373392"})

print(f"Contact book is : \n {contacts}")


user_search_name= input("name to search : ")
user_search_number= input("number to search :")

print(f"search result : {contacts['names'].get(user_search_name, 'Name not found')} , {contacts['Numbers'].get(user_search_number, 'Number not found')}")

data = {
    "student1" : {"name" : "Ahmed" , "grades" : [100,90,80]},
    "student2" : {"name" : "Mohamed" , "grades" : [90,80,70]},
}
avg1 = (data["student1"]["grades"][0] + data["student1"]["grades"][1] + data["student1"]["grades"][2] ) / 3
avg2 = (data["student2"]["grades"][0] + data["student2"]["grades"][1] + data["student2"]["grades"][2] ) / 3

print(f"Student 1 : {data['student1']['name']} , Average : {avg1}")
print(f"Student 2 : {data['student2']['name']} , Average : {avg2}")